SIRI-548 allow encoding of mails with umlauts to idn
scireum/sirius-web pull request #1014
Opened 2022-03-24 09:21 UTC by ymo-sci

- fixes: SIRI-548

2022-03-28 09:16 UTC, mkeckmkeck requested changes

2022-03-28 09:16 UTC, mkeckmkeck commented on src/main/java/sirius/web/mails/MailSender.java
> +    private String encodeIdnMailAddressToAsciiIfNecessary(String mailAddress) {
```suggestion
    private String sanetizeMailAddress(String mailAddress) {
```

2022-03-28 09:16 UTC, mkeckmkeck commented on src/main/java/sirius/web/mails/MailSender.java
> +            String user = mailAddress.substring(0, mailAddress.indexOf("@"));
```suggestion
            String preDomainPart = mailAddress.substring(0, mailAddress.indexOf("@") + 1);
```
Then there is no need to add the @ again

2022-03-28 09:27 UTC, jakobvogel commented on src/main/java/sirius/web/mails/MailSender.java
> +    private String encodeIdnMailAddressToAsciiIfNecessary(String mailAddress) {
https://dict.leo.org/german-english/sanetize → sanitize 🙃 (oder sanitise 🇬🇧)

2022-03-28 09:41 UTC, sabieber approved these changes

2022-03-28 09:42 UTC, andyHa approved these changes

2022-03-28 10:10 UTC, idlira approved these changes

2022-03-28 22:51 UTC, jakobvogel approved these changes

2022-03-29 06:44 UTC, mkeckmkeck approved these changes

2022-03-29 06:44 UTC, merged