SIRI-595 Update Bootstrap, update token-autocomplete, minor bugfixes & enhancements
scireum/sirius-web pull request #1075
Opened 2022-08-01 13:20 UTC by qw3ry

This prepares the [switch to tycho for /jobs in sirius-biz](https://github.com/scireum/sirius-biz/pull/1444)
- Update [Token-autocomplete](https://github.com/scireum/token-autocomplete)
- Update Bootstrap from 4.4.1 to 4.6.0
- Bugfixing + new feature in core.js
- Allow further customizing of a `<t:singleSelect>`

2022-08-01 13:37 UTC, qw3ry commented
_strictly speaking_, this PR is breaking, because the usage of `sirius.querySelector` returned undefined before, which would usually cause an exception. Also, if someone dared to name a variable inside a tycho-singleselect script `autocomplete`, this should fail as well (I haven't tested this). However, these seem so unlikely to me that I omit the "Breaking Change" label. Feel free to add it if you disagree.

2022-08-03 07:48 UTC, jmuscireum approved these changes

2022-08-03 07:49 UTC, mkeckmkeck approved these changes

2022-08-03 13:18 UTC, cschierle approved these changes

2022-08-04 07:02 UTC, fhaScireum requested changes

2022-08-04 07:02 UTC, fhaScireum commented on src/main/resources/default/assets/common/core.js.pasta
> +    for (const key of formData.keys()) {
`const` in for-loop declaration is not supported in IE11: https://caniuse.com/const

2022-08-05 07:47 UTC, sabieber approved these changes

2022-08-05 07:53 UTC, fhaScireum approved these changes

2022-08-05 07:54 UTC, fhaScireum reviewed
Lieber let :)

2022-08-05 07:54 UTC, fhaScireum commented on src/main/resources/default/assets/common/core.js.pasta
> +    for (var key of formData.keys()) {
```suggestion
    for (let key of formData.keys()) {
```

2022-08-05 07:55 UTC, sabieber commented on src/main/resources/default/assets/common/core.js.pasta
> +    for (var key of formData.keys()) {
Ne das darf man im IE11 glaub auch net

2022-08-05 07:58 UTC, sabieber requested changes
let in for wird vom IE 11 net unterstützt

2022-08-05 08:00 UTC, fhaScireum commented
> let in for wird vom IE 11 net unterstützt

https://caniuse.com/?search=let . So wie ich das verstehe verhält sich let in for-loops einfach wie var.

2022-08-05 08:01 UTC, fhaScireum approved these changes

2022-08-05 08:07 UTC, sabieber commented
> > let in for wird vom IE 11 net unterstützt
> 
> https://caniuse.com/?search=let . So wie ich das verstehe verhält sich let in for-loops einfach wie var. Passt aber mit var statt let.

Wir hatten schon Probleme mit let in for im IE 11, aber weiß nicht mehr das genaue Szenario. Seit dem bin ich einfach vorsichtig und nehm immer `var` in for loop und `const`/`let` überall sonst.

2022-08-05 08:07 UTC, sabieber approved these changes

2022-08-05 08:24 UTC, fhaScireum commented
> Wir hatten schon Probleme mit let in for im IE 11, aber weiß nicht mehr das genaue Szenario. Seit dem bin ich einfach vorsichtig und nehm immer `var` in for loop und `const`/`let` überall sonst.

Danke für die Info. Dann bin ich da nun auch vorsichtiger 👍

2022-08-05 11:46 UTC, mko-sci approved these changes

2022-08-05 11:49 UTC, merged