Whitelists the inlineResource macro
scireum/sirius-web pull request #1167
Opened 2023-02-06 13:45 UTC by jmuscireum

This allows the inlineResource macro in sandboxes, but only if static resources are referenced. It should never be required for user-created templates to inline tagliatelle resources.

2023-02-06 13:51 UTC, sabieber approved these changes

2023-02-06 13:52 UTC, mkeckmkeck approved these changes

2023-02-07 08:59 UTC, andyHa requested changes

2023-02-07 08:59 UTC, andyHa commented on src/main/java/sirius/pasta/noodle/macros/InlineResourceMacro.java
> +            } else if (String.valueOf(args.get(0).getConstantValue()).endsWith(PASTA_SUFFIX)) {
shouldn't be a ! in there?

2023-02-07 08:59 UTC, andyHa commented on src/main/java/sirius/pasta/noodle/macros/InlineResourceMacro.java
> +            } else if (String.valueOf(args.get(0).getConstantValue()).endsWith(PASTA_SUFFIX)) {
and shouldn't we check like "either .pasta" or "/assets" ?

2023-02-07 08:59 UTC, andyHa commented on src/main/java/sirius/pasta/noodle/macros/InlineResourceMacro.java
> +            } else if (String.valueOf(args.get(0).getConstantValue()).endsWith(PASTA_SUFFIX)) {
(also, don't we have such a check elsewhere in Tagliatelle?

2023-02-07 08:59 UTC, andyHa commented on src/main/java/sirius/pasta/noodle/macros/InlineResourceMacro.java
> +                                        "Only constant resources are supported due to sandbox restrictions.");
shouldn't this be more specific like "only pasta templates...."

2023-02-07 09:23 UTC, andyHa approved these changes

2023-02-08 10:57 UTC, merged