SIRI-724: improve logging for jsoncall
scireum/sirius-web pull request #1174
Opened 2023-02-15 15:17 UTC by qw3ry

Needs https://github.com/scireum/sirius-kernel/pull/438

2023-02-15 15:18 UTC, sabieber approved these changes

2023-02-15 15:18 UTC, sabieber commented on src/main/java/sirius/web/services/JSONCall.java
> +     * Log the outcall to {@code logger}.
```suggestion
     * Logs the outcall to {@code logger}.
```

2023-02-15 15:28 UTC, jakobvogel approved these changes

2023-02-15 15:28 UTC, jakobvogel commented on src/main/java/sirius/web/services/JSONCall.java
> +     * @return returns the JSON call itself for fluent method calls
```suggestion
     * @return the JSON call itself for fluent method calls
```

2023-02-15 16:44 UTC, andyHa requested changes

2023-02-15 16:44 UTC, andyHa commented on src/main/java/sirius/web/services/JSONCall.java
> +        }
extract method & ensure that the call isn't executed twice....

2023-02-17 10:14 UTC, mkeckmkeck approved these changes

2023-02-17 10:16 UTC, idlira approved these changes

2023-02-17 12:45 UTC, andyHa approved these changes

2023-02-17 12:45 UTC, andyHa commented on src/main/java/sirius/web/services/JSONCall.java
> +        logRequest(body);
```suggestion
        logRequest(body);
        
```

2023-02-17 13:32 UTC, mko-sci approved these changes

2023-02-20 07:34 UTC, merged