Automatically grows the contents next to the sidebar to 100% height.
scireum/sirius-web pull request #1221
Opened 2023-05-22 08:59 UTC by andyHa

BEFORE:
![grafik](https://github.com/scireum/sirius-web/assets/875799/7aff292e-678a-4096-ac74-68504d90334e)

AFTER:
![grafik](https://github.com/scireum/sirius-web/assets/875799/84548ac3-21b7-40a3-bfaf-dc76b3cf89f5)

2023-05-22 09:02 UTC, jakobvogel approved these changes

2023-05-22 10:21 UTC, jmuscireum approved these changes

2023-05-22 10:38 UTC, mko-sci approved these changes

2023-05-22 11:14 UTC, sabieber approved these changes

2023-05-22 11:14 UTC, sabieber requested changes

2023-05-22 11:14 UTC, sabieber commented on src/main/resources/default/taglib/t/sidebar.html.pasta
> +        <div class="d-flex flex-column flex-grow-1 h-100">
```suggestion
        <div class="d-flex flex-column h-100">
```
Flex Grow property without a flex container is pretty pointless and will be ignored by the browser

2023-05-22 11:21 UTC, fhaScireum approved these changes

2023-05-23 12:30 UTC, ymo-sci approved these changes

2023-05-30 12:43 UTC, sabieber approved these changes

2023-05-30 12:44 UTC, merged