JUnit: Migrate ScopeInfoTest to Kotlin
scireum/sirius-web pull request #1357
Opened 2024-01-08 15:09 UTC by scireum-mbo

Fixes: OX-10357

2024-01-08 15:12 UTC, sabieber requested changes

2024-01-08 15:12 UTC, sabieber commented on src/test/kotlin/sirius/web/security/ScopeInfoTest.kt
> +        helper3 != null
**Required:** Here the assertion is missing

2024-01-08 15:52 UTC, sabieber approved these changes

2024-01-08 16:40 UTC, idlira approved these changes

2024-01-09 06:33 UTC, mkeckmkeck approved these changes

2024-01-09 06:33 UTC, merged