Fixes description and javadoc for the i:switch tag
scireum/sirius-web pull request #753
Opened 2020-09-25 10:07 UTC by meg1502

2020-09-25 10:08 UTC, andyHa approved these changes

2020-09-25 10:08 UTC, idlira approved these changes

2020-09-25 10:34 UTC, cschierle requested changes

2020-09-25 10:34 UTC, cschierle commented on src/main/java/sirius/tagliatelle/emitter/SwitchEmitter.java
> + * Represents a switch block where inner blocks are only rendered if their name matche the switch expression.
```suggestion
 * Represents a switch block where inner blocks are only rendered if their name match the switch expression.
```
Typo

2020-09-25 11:05 UTC, bwiedmann approved these changes

2020-09-28 12:23 UTC, bwiedmann approved these changes

2020-10-01 06:33 UTC, cschierle approved these changes

2020-10-01 07:51 UTC, merged