Allows to save a resource to a physical file
scireum/sirius-web pull request #754
Opened 2020-10-06 14:21 UTC by idlira

Fixes: SIRI-205

2020-10-06 14:24 UTC, bwiedmann approved these changes

2020-10-06 14:26 UTC, mkeckmkeck approved these changes

2020-10-06 14:45 UTC, sabieber approved these changes

2020-10-06 15:14 UTC, andyHa commented on src/main/java/sirius/web/resources/Resource.java
> +        try (OutputStream outputStream = new FileOutputStream(outputFile); InputStream inputStream = openStream()) {
Streams.transfer

2020-10-06 15:14 UTC, andyHa requested changes
...

2020-10-06 15:48 UTC, sabieber approved these changes

2020-10-07 05:21 UTC, bwiedmann approved these changes

2020-10-07 07:45 UTC, merged