Provides a robust command parser and uses it for the /system/console
scireum/sirius-web pull request #766
Opened 2020-11-23 14:51 UTC by andyHa

This now supports parameters which contain whitespaces.

2020-11-23 15:07 UTC, sabieber approved these changes

2020-11-23 15:16 UTC, idlira requested changes
mini typo

Cool future enhancement could be the ability to define named parameters (such as Python's parser module) and print clicable URLs in log output :-)

2020-11-23 15:16 UTC, idlira commented on src/main/java/sirius/web/health/console/CommandParser.java
> + * whitespaces. If a parameter value itself contains whitepsaces, it can be put into quotes:
```suggestion
 * whitespaces. If a parameter value itself contains whitespaces, it can be put into quotes:
```

2020-11-24 20:58 UTC, jakobvogel approved these changes

2020-11-24 20:58 UTC, jakobvogel commented on src/main/java/sirius/web/health/console/CommandParser.java
> +        LookaheadReader reader = new LookaheadReader(new StringReader(input));
`input` can be `null` here if I am not mistaken. Is this a problem?

2020-11-24 21:04 UTC, sabieber approved these changes

2020-11-24 21:19 UTC, jakobvogel approved these changes

2020-11-25 06:18 UTC, mkeckmkeck approved these changes

2020-11-25 06:19 UTC, merged