SIRI-307 allow w:page to avoid search engine indexing
scireum/sirius-web pull request #800
Opened 2021-02-01 10:52 UTC by qw3ry

2021-02-01 15:35 UTC, sabieber approved these changes

2021-02-01 15:36 UTC, andyHa requested changes

2021-02-01 15:36 UTC, andyHa commented on src/main/resources/default/taglib/w/page.html.pasta
> +<i:arg type="boolean" name="noindex" default="false"
Also add to taglib/t/page

2021-02-01 15:38 UTC, meg1502 approved these changes

2021-02-02 05:22 UTC, mkeckmkeck approved these changes

2021-02-02 09:32 UTC, andyHa approved these changes

2021-02-02 09:32 UTC, merged