Extracts the PDF image replace logic into separate handlers
scireum/sirius-web pull request #812
Opened 2021-02-15 10:39 UTC by jmuscireum

This allows for easy integration of custom logic (for example embedding blobs without the use of http).

Migration:
If internal resources (assets) are used via relative URLs these need to be prepended with resource://.

Barcodes and QR codes using the type attribute in the img tag are now instead generated by using the barcode:// and qr:// URI protocols.

2021-02-15 10:55 UTC, sabieber requested changes

2021-02-15 10:55 UTC, sabieber commented on src/main/java/sirius/web/templates/pdf/ImageReplacedElementFactory.java
> +        for (PdfReplaceHandler handler : handlers) {
Stream::findFirst -> orElseThrow?

2021-02-15 10:55 UTC, sabieber commented on src/main/java/sirius/web/templates/pdf/handlers/BarcodePdfReplaceHandler.java
> +     * Pad the code if necessary.
Pad -> Pads

2021-02-15 10:55 UTC, sabieber commented on src/main/java/sirius/web/templates/pdf/handlers/BarcodePdfReplaceHandler.java
> + * Responsible for resolving barcode:// URIs.
Resolves barcode:// URIs to ....

2021-02-15 10:55 UTC, sabieber commented on src/main/java/sirius/web/templates/pdf/handlers/HttpPdfReplaceHandler.java
> + * Responsible for resolving http:// and https:// URIs and resizing the image while maintaining the image ratio.
Resolves http:// and https:// URIs ....

2021-02-15 10:55 UTC, sabieber commented on src/main/java/sirius/web/templates/pdf/handlers/QrCodePdfReplaceHandler.java
> + * Responsible for resolving qr:// URIs.
Resolves qr:// URIs to ...

2021-02-15 10:55 UTC, sabieber commented on src/main/java/sirius/web/templates/pdf/handlers/ResourcePdfReplaceHandler.java
> + * Responsible for resolving resource:// URIs using {@link Resources} and resizing the image while maintaining the image
Resolves ...

2021-02-15 12:09 UTC, sabieber approved these changes

2021-02-15 16:59 UTC, idlira approved these changes

2021-02-16 06:28 UTC, mkeckmkeck approved these changes

2021-02-16 07:56 UTC, bwiedmann approved these changes

2021-02-16 08:11 UTC, andyHa approved these changes

2021-02-16 08:11 UTC, merged