Fixes a NPE when an image URL returns 404 when generating a PDF
scireum/sirius-web pull request #828
Opened 2021-04-07 11:26 UTC by fgoerner

Fixes: SE-10528

2021-04-07 11:31 UTC, jmuscireum requested changes

2021-04-07 11:31 UTC, jmuscireum commented on src/main/java/sirius/web/templates/pdf/handlers/PdfReplaceHandler.java
> +        if (fsImage == null) {
Also remove the two `@Nonnull` of resizeImage

2021-04-07 11:37 UTC, sabieber approved these changes

2021-04-07 11:45 UTC, andyHa approved these changes

2021-04-07 11:47 UTC, mkeckmkeck approved these changes

2021-04-08 10:52 UTC, jmuscireum approved these changes

2021-04-08 10:52 UTC, merged